### ISSUE TITLE
Can't see friends on tab bar and some other issues

### ISSUE THREAD

**Issue by NaufalAns** [FusioonDev/Point-Blank-Revolution#1]
1. Can't see friends on tab bar.
2. In bomb mission mode, the round can exceed the round limit and still can play.
3. In defense mode, black panther map, the box does not spawn rpg.
4. In space mode, no box appears.

That's the problem I found. I hope it's resolved quickly.
Sorry if my english is not good.
Thank you.

**Comment by FusioonDev** [comment]
Issue 1 and 2 fixed, check out the new dev release.

For issue 3/4 create 2 separated issue, this modes are not my priority so for now I'll not work on them.
